### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NikitoDev** [BrunoSobrino/SimpleBot#4]
Al enviar un gif/video me muestra el siguiente error y  no se envia el sticker.

<Buffer 3c 21 44 4f 43 54 59 50 45 20 68 74 6d 6c 3e 0a 09 3c 68 74 6d 6c 3e 0a 09 20 20 3c 68 65 61 64 3e 0a 09 09 3c 6d 65 74 61 20 6e 61 6d 65 3d 22 76 69 ... 456 more bytes>
<!DOCTYPE html>
        <html>
          <head>
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta charset="utf-8">
                <title>Application Error</title>
                <style media="screen">
                  html,body,iframe {
                        margin: 0;
                        padding: 0;
                  }
                  html,body {
                        height: 100%;
                        overflow: hidden;
                  }
                  iframe {
                        width: 100%;
                        height: 100%;
                        border: 0;
                  }
                </style>
          </head>
          <body>
                <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
          </body>
        </html>
<Buffer 3c 73 63 72 69 70 74 20 74 79 70 65 3d 22 31 34 62 36 35 32 61 30 63 63 36 33 34 63 61 65 62 64 65 61 33 36 64 34 2d 74 65 78 74 2f 6a 61 76 61 73 63 ... 502866 more bytes>
{
  data: <Buffer 52 49 46 46 38 26 10 00 57 45 42 50 56 50 38 58 0a 00 00 00 12 00 00 00 ff 01 00 ff 01 00 41 4e 49 4d 06 00 00 00 ff ff ff ff 01 00 41 4e 4d 46 c6 2c ... 1058318 more bytes>,
  filename: 'C:\\Users\\User\\Desktop\\Bot\\tmp\\1668734563139.jpeg.webp'
}
<Buffer >
<Buffer 3c 21 44 4f 43 54 59 50 45 20 68 74 6d 6c 3e 0a 09 3c 68 74 6d 6c 3e 0a 09 20 20 3c 68 65 61 64 3e 0a 09 09 3c 6d 65 74 61 20 6e 61 6d 65 3d 22 76 69 ... 456 more bytes>
<!DOCTYPE html>
        <html>
          <head>
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta charset="utf-8">
                <title>Application Error</title>
                <style media="screen">
                  html,body,iframe {
                        margin: 0;
                        padding: 0;
                  }
                  html,body {
                        height: 100%;
                        overflow: hidden;
                  }
                  iframe {
                        width: 100%;
                        height: 100%;
                        border: 0;
                  }
                </style>
          </head>
          <body>
                <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
          </body>
        </html>
TypeError: Result is not a buffer
    at Object.conn.getFile (C:\Users\User\Desktop\Bot\lib\simple.js:141:43)
    at Object.conn.sendFile (C:\Users\User\Desktop\Bot\lib\simple.js:211:31)
    at Object.handler (C:\Users\User\Desktop\Bot\plugins\sticker.js:35:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.handler (C:\Users\User\Desktop\Bot\handler.js:404:25) unhandledRejection

**Comment by NikitoDev** [comment]
Alguna solucion que me pueda ayudar @BrunoSobrino?
